I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 25, in script call
    call stb2_page1
  File "game/stb2_page1.rpy", line 7, in script
    scene bg stb2_page 1 with fade
OSError: Couldn't find file 'images/sample_moovie_pp.webm'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 25, in script call
    call stb2_page1
  File "game/stb2_page1.rpy", line 7, in script
    scene bg stb2_page 1 with fade
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\ast.py", line 1678, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\exports.py", line 1757, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 2975, in do_with
    return self.interact(trans_pause=True,
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 3579, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\display\core.py", line 4099, in interact_core
    renpy.audio.audio.interact()
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\audio\audio.py", line 1269, in interact
    periodic()
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\audio\audio.py", line 1222, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\audio\audio.py", line 1200, in periodic_thread_main
    periodic_pass()
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\audio\audio.py", line 1142, in periodic_pass
    c.periodic()
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\audio\audio.py", line 534, in periodic
    topf = load(filename)
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "D:\RenPy\renpy-8.1.1-sdk\renpy\loader.py", line 833, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'images/sample_moovie_pp.webm'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
RachaBardDemo 1.0
Mon Sep  4 15:12:41 2023
